### ISSUE TITLE
Only works for 2 masks

### ISSUE THREAD

**Issue by mo2561057** [iza-institute-of-labor-economics/lcm#3]
https://github.com/iza-institute-of-labor-economics/lcm/blob/b187c937394c6dcfa7efe083d0ec4e1fe7e208dd/src/lcm/create_state_space.py#L204

When we use jax logical_and we cannot use more than 2 masks. At least it fails when I try to. Can we just use functools reduce or is there a better way?

**Comment by janosg** [comment]
Fixed. Thanks!
